name: InnerEcho
description: "A application for breathing exercises and meditation caring mental health."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # Ensure Dart and Flutter compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  youtube_player_iframe: ^5.2.0  # Keep youtube_player_iframe at 5.2.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.9.0  # Compatible with youtube_player_iframe
  google_generative_ai: ^0.4.6
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Use the latest version

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
